const { nextui } = require("@nextui-org/react");
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "bg-acid/10",
    "bg-cold/10",
    "bg-fire/10",
    "bg-force/10",
    "bg-brute/10",
    "bg-poison/10",
    "bg-radient/10",
    "bg-necrotic/10",
    "bg-lightning/10",
    "bg-thunder/10",
    "bg-psychic/10",
    "border-acid",
    "border-cold",
    "border-fire",
    "border-force",
    "border-brute",
    "border-poison",
    "border-radient",
    "border-necrotic",
    "border-lightning",
    "border-thunder",
    "border-psychic",
  ],
  theme: {
    fontSize: {
      sm: "clamp(0.67rem, 0.14vw + 0.64rem, 0.75rem)",
      base: "clamp(0.88rem, 0.23vw + 0.82rem, 1rem)",
      md: "clamp(1.14rem, 0.36vw + 1.05rem, 1.33rem)",
      lg: "clamp(1.48rem, 0.54vw + 1.34rem, 1.78rem)",
      xl: "clamp(1.92rem, 0.81vw + 1.72rem, 2.37rem)",
      "2xl": "clamp(2.5rem, 1.2vw + 2.2rem, 3.16rem)",
      "3xl": "clamp(3.25rem, 1.75vw + 2.81rem, 4.21rem)",
      "4xl": "2.441rem",
      "5xl": "3.052rem",
    },
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        neonpurple: {
          300: "#9517A6",
          400: "#C530D9",
          500: "#DC38F2",
        },
        neongreen: "#68E0A6",
        neonyellow: "#C9CB5E",
        neonorange: "#E6AD6A",
        neonred: "#E66A6A",
        neonblue: "#04D9FF",
        background: "#241626",
        overlay: "#333333",
        /* Spell colors */
        acid: "#ECF335",
        cold: "#2AC4FF",
        fire: "#EE9C3B",
        force: "#C85256",
        brute: "#F22D1B",
        poison: "#D0F524",
        radient: "#EBDE83",
        necrotic: "#4FB57D",
        lightning: "#3767E3",
        thunder: "#C195E1",
        psychic: "#F2A7ED",
      },
      fontFamily: {
        poppins: ["var(--poppins)"],
        almendra: ["var(--almendra)"],
      },
      gridTemplateColumns: {
        startscreen: "66% 33%",
        equipmentRow: "2fr 1.5fr 0.5fr 1fr",
        equipmentRowPopup: "2fr 1fr 1fr",
        actionsRow: "2fr 1fr 1fr 1fr",
      },
    },
  },
  darkMode: "class",
  plugins: [nextui()],
};
